### ISSUE TITLE
requirements.txt prevents installation on updated systems

### ISSUE THREAD

**Issue by towerbe** [peak-ai/eks-token#14]
**Describe the bug**
The hardcoded versions of awscli and botocore in the requirements.txt prevent the installation of eks-token on any system with newer versions of either  or both.

**System information**
Windows 10
Amazon Linux 2
Sure this exists on other OSes as well

#### Steps to reproduce the issue

1.  pip3 install eks-token
2. 
3. 

#### What's the expected result?

-Completed installation of eks-token

#### What's the actual result?

- failed installation

#### Additional details / screenshot

- I have submitted a PR to fix the issue.

Thank you for your contribution!

**Comment by azhar22k** [comment]
Hey @towerbe 
Thanks for reporting this.
Do you happen to have some screenshots or error logs for us to take a look?

Also, the description says
> I have submitted a PR to fix the issue.

But we can't see any PRs from you.

**Comment by azhar22k** [comment]
https://github.com/peak-ai/eks-token/pull/15 fixes this
